apiVersion: v1
kind: Service
metadata:
  name: promotion-storage
  labels:
    app: promotion-storage
spec:
  selector:
    app: promotion-storage
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 31001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-storage
  labels:
    app: promotion-storage
spec:
  selector:
    matchLabels:
      app: promotion-storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: promotion-storage
        tier: promotion-storage
    spec:
      serviceAccountName: promotion-storage
      containers:
        - image: 127.0.0.1:30400/promotion-storage:$BUILD_TAG 
          name: promotion-storage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: pm-storage